function Writing_Out_Data(FolderPath,File,Mat_phase_fractions,Mat_av_if_length_mu,Mat_av_if_length_relative_mu,Mat_angles_rel_hist,Mat_dist_average_mu,Mat_Nearest_Neighbours,Mat_Area_mu,Mat_Major_axes_mu,Mat_Minor_axes_mu,Mat_Orientations,Mat_AspectRatio,Mat_average_Axes_length_mu,Mat_average_shape_factor,av_curvature,max_curvature,min_curvature,Matrix_Moment_Invariants_Shape_Factors,Triple_points_mu)

write_dir =sprintf('%s.csv',char(strcat(FolderPath,'\',File(1))));
fid = fopen(write_dir, 'wt');
fprintf(fid, 'Lengths in micrometers, Areas in square micrometers\n');
fprintf(fid, '%s\n', 'Phase fractions');
fprintf(fid, '%s,%s,%s\n', 'black', 'gray', 'white');
fprintf(fid, '%g,%g,%g\n', transpose(Mat_phase_fractions));
fprintf(fid, '\n%s\n','Average interface length');
fprintf(fid, '%s,%s,%s,%s,%s,%s\n','b at bg interf','b at bw interf','g at gb interf','g at gw interf','w at wb interf','w at wg interf');
fprintf(fid, '%g,%g,%g,%g,%g,%g\n',Mat_av_if_length_mu(1,1),Mat_av_if_length_mu(2,1),Mat_av_if_length_mu(4,1),Mat_av_if_length_mu(6,1),Mat_av_if_length_mu(8,1),Mat_av_if_length_mu(9,1));
fprintf(fid, '\n%s\n','Average interface length per particle size');
fprintf(fid, '%s,%s,%s,%s,%s,%s,%s,%s,%s\n','b at bg interf','b at bw interf','b','g at gb interf','g at gw interf','g','w at wb interf','w at wg interf','w');
fprintf(fid, '%g,%g,%g,%g,%g,%g,%g,%g,%g\n',Mat_av_if_length_relative_mu(1,1),Mat_av_if_length_relative_mu(2,1),Mat_av_if_length_relative_mu(4,1),Mat_av_if_length_relative_mu(5,1),Mat_av_if_length_relative_mu(7,1),Mat_av_if_length_relative_mu(8,1),Mat_av_if_length_relative_mu(10,1),Mat_av_if_length_relative_mu(11,1),Mat_av_if_length_relative_mu(12,1));
fprintf(fid, '\n%s\n','Average shape factor');
fprintf(fid, '%s,%s,%s\n','b','g','w');
fprintf(fid, '%g,%g,%g\n',Mat_average_shape_factor);
fprintf(fid, '\n%s\n','Triple point denisty');
fprintf(fid, '%s,%s\n','Number triple points','Density in TP/mum^2');
fprintf(fid, '%g,%g\n',Triple_points_mu(1,1),Triple_points_mu(2,1));
fprintf(fid, '\n%s\n','Orientation of the interfaces');
fprintf(fid, '%s,%s,%s,%s\n','angles','black phase','gray phase','white phase');
fprintf(fid, '%g,%g,%g,%g,\n',transpose([Mat_angles_rel_hist(:,1)*10,Mat_angles_rel_hist(:,2),Mat_angles_rel_hist(:,3),Mat_angles_rel_hist(:,4)]));
fprintf(fid, '\n%s\n','Same-phase Centroid Spacings');
fprintf(fid, '%s,%s,%s,%s\n','black w black mid','black w gray mid','black w white mid','black overall');
fprintf(fid, '%g,%g,%g,%g\n',Mat_dist_average_mu(1,:));
fprintf(fid, '%s,%s,%s,%s\n','gray w black mid','gray w gray mid','gray w white mid','gray overall');
fprintf(fid, '%g,%g,%g,%g\n',Mat_dist_average_mu(2,:));
fprintf(fid, '%s,%s,%s,%s\n','white w black mid','white w gray mid','white w white mid','white overall');
fprintf(fid, '%g,%g,%g,%g\n',Mat_dist_average_mu(3,:));
fprintf(fid, '\n%s\n','Nearest Neighbors');
fprintf(fid, '%s,%s,%s,%s,\n','number of neighbors','b with x b neighbors','b with x g neighbors','b with x w neighbors');
fprintf(fid, '%g,%g,%g,%g\n',transpose(Mat_Nearest_Neighbours(:,:,1)));
fprintf(fid, '\n%s,%s,%s,%s,\n','number of neighbors','g with x b neighbors','g with x g neighbors','g with x w neighbors');
fprintf(fid, '%g,%g,%g,%g\n',transpose(Mat_Nearest_Neighbours(:,:,2)));
fprintf(fid, '\n%s,%s,%s,%s,\n','number of neighbors','w with x b neighbors','w with x g neighbors','w with x w neighbors');
fprintf(fid, '%g,%g,%g,%g\n',transpose(Mat_Nearest_Neighbours(:,:,3)));
fprintf(fid, '\n%s\n','Axis Lengths');
fprintf(fid, '%s,%s,%s,%s,%s,%s\n','Major black','Major gray','Major white','Minor black','Minor gray','Minor white');
fprintf(fid, '%g,%g,%g,%g,%g,%g\n',Mat_average_Axes_length_mu(1,1),Mat_average_Axes_length_mu(1,3),Mat_average_Axes_length_mu(2,1),Mat_average_Axes_length_mu(2,3),Mat_average_Axes_length_mu(3,1),Mat_average_Axes_length_mu(3,3));
fprintf(fid, '\n%s\n','Particle Areas');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',Mat_Area_mu(:,:));
fprintf(fid, '\n%s\n','Particle Major Axes');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',Mat_Major_axes_mu(:,:));
fprintf(fid, '\n%s\n','Particle Minor Axes');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',Mat_Minor_axes_mu(:,:));
fprintf(fid, '\n%s\n','Particle Aspect Ratios');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',Mat_AspectRatio(:,:));
fprintf(fid, '\n%s\n','Particle Orientations (degrees)');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',Mat_Orientations(:,:));

% av_curvature,max_curvature,min_curvature
fprintf(fid, '\n%s\n','Average curvature');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',av_curvature(:,:));
fprintf(fid, '\n%s\n','Maximum curvature');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',max_curvature(:,:));
fprintf(fid, '\n%s\n','Minimum curvature');
fprintf(fid, '%s,%s,%s\n','black','gray','white');
fprintf(fid, '%g,%g,%g\n',min_curvature(:,:));
fprintf(fid, '\n%s\n','Shape factors based on second moment of inertia');
fprintf(fid, '%s,%s,%s,%s,%s,%s\n','black O1','black O2','gray O1','gray O2','white O1','white O2');
fprintf(fid, '%g,%g,%g,%g,%g,%g\n',[Matrix_Moment_Invariants_Shape_Factors(1,:,1);Matrix_Moment_Invariants_Shape_Factors(1,:,2);Matrix_Moment_Invariants_Shape_Factors(2,:,1);Matrix_Moment_Invariants_Shape_Factors(2,:,2);Matrix_Moment_Invariants_Shape_Factors(3,:,1);Matrix_Moment_Invariants_Shape_Factors(3,:,2)]);
fclose(fid);
